[workspace]
members = ["riic-fetch", "src-tauri"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Kyle Chen"]
license = "GPL-3.0-or-later"
repository = "https://github.com/ark-db/riic-engine"
edition = "2021"
publish = false

[workspace.dependencies]
ahash = "0.8.3"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
strip = true
