[package]
name = "riic-fetch"
version = "0.1.0"
description = "Asset-fetching program for RIIC Engine"
authors = ["Kyle Chen"]
license = "GPL-3.0-or-later"
repository = "https://github.com/ark-db/riic-engine"
edition = "2021"
publish = false

[dependencies]
ahash = { version = "0.8.3", features = ["serde"] }
futures = "0.3.27"
reqwest = { version = "0.11.14", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["macros", "rt-multi-thread"] }
toml = "0.7.3"
