[package]
name = "riic-fetch"
version.workspace = true
description = "Asset-fetching program for RIIC Engine"
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0.75"
rayon = "1.8.0"
ureq = { version = "2.8.0", features = ["json"] }
