terms_path = "../src/lib/data/terms.json"
styles_path = "../src/lib/data/text-colors.json"
item_whitelist = []
min_image_size = 60

[operator]
data_path = "../src/lib/data/chars.json"
image_dir = "../static/chars"
quality = 25

[skill]
data_path = "../src/lib/data/skills.json"
image_dir = "../static/skills"
quality = 50

[item]
image_dir = "../static/items"
quality = 50

[facility]
data_path = "../src/lib/facilities.json"
image_dir = "../static/facilities"
quality = 100

[name_overrides]